CREATE DATABASE retaggru_rgffxiv;

USE retaggru_rgffxiv;

CREATE TABLE bozjafrags (
	id TINYINT PRIMARY KEY NOT NULL,
	actionicons VARCHAR(50) NOT NULL,
    actions VARCHAR(50) NOT NULL,
    fragicons VARCHAR(50) NOT NULL,
    fragments VARCHAR(50) NOT NULL,
    resistancerank TINYINT NOT NULL,
	sourcezone VARCHAR(50) NOT NULL,
    sourcedrop VARCHAR(100) NOT NULL
);

CREATE TABLE bozja_actions (
	actionicons VARCHAR(50) NOT NULL,
    actions VARCHAR(50) NOT NULL,
    castrange VARCHAR(50) NOT NULL,
    radius VARCHAR(50) NOT NULL,
    cast VARCHAR(50) NOT NULL,
    recast VARCHAR(50) NOT NULL,
    available VARCHAR(50) NOT NULL,
    affinity VARCHAR(50) NOT NULL,
    tooltip VARCHAR(250) NOT NULL
);

UPDATE bozjafrags SET actionicons='lostslash.png' WHERE id=4;

INSERT INTO bozjafrags (id,actionicons,actions,fragicons,fragments,resistancerank,sourcezone,sourcedrop)
VALUES
(1,'lostfocus.png','Lost Focus','forgottenfragmenta.png','Forgotten Fragment of Violence',8,'Bozjan Southern Front','North Ashkin, North Star Mobs'),
(2,'lostfontofmagic.png','Lost Font of Magic','forgottenfragmenta.png','Forgotten Fragment of Sagacity',12,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(3,'lostfontofpower.png','Lost Font of Power','forgottenfragmenta.png','Forgotten Fragment of Sagacity',12,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(4,'lostslash.png','Lost Slash','forgottenfragmenta.png','Forgotten Fragment of Violence',8,'Bozjan Southern Front','North Ashkin, North Star Mobs'),
(5,'lostdeath.png','Lost Death','forgottenfragmenta.png','Forgotten Fragment of Violence',8,'Bozjan Southern Front','North Ashkin, North Star Mobs'),
(6,'bannerofnobleends.png','Banner of Noble Ends','forgottenfragmenta.png','Forgotten Fragment of Resolve',8,'Bozjan Southern Front','CE: Trampled Under Hoof<br>CE: Where Strode the Behemoth<br>CE: Metal Fox Chaos'),
(7,'bannerofhonoredsacrifice.png','Banner of Honored Sacrifice','forgottenfragmenta.png','Forgotten Fragment of Resolve',8,'Bozjan Southern Front','CE: Trampled Under Hoof<br>CE: Where Strode the Behemoth<br>CE: Metal Fox Chaos'),
(8,'bannerofhonedacuity.png','Banner of Honed Acuity','forgottenfragmenta.png','Forgotten Fragment of Resolve',8,'Bozjan Southern Front','CE: Trampled Under Hoof<br>CE: Where Strode the Behemoth<br>CE: Metal Fox Chaos'),
(9,'lostfairtrade.png','Lost Fair Trade','forgottenfragmenta.png','Forgotten Fragment of Caprice',15,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(10,'lostflarestar.png','Lost Flare Star','forgottenfragmentb.png','Forgotten Fragment of Clarity',15,'Bozjan Southern Front<br>Delubrum Reginae','Trade for 3 Bozjan Clusters<br>Rare Drop from Loot Coffers'),
(11,'lostmanawall.png','Lost Manawall','forgottenfragmenta.png','Forgotten Fragment of Caution',2,'Bozjan Southern Front','South Star Mobs'),
(12,'banneroftirelessconviction.png','Banner of Tireless Conviction','forgottenfragmenta.png','Forgotten Fragment of Resolve',8,'Bozjan Southern Front','CE: Trampled Under Hoof<br>CE: Where Strode the Behemoth<br>CE: Metal Fox Chaos'),
(13,'banneroffirmresolve.png','Banner of Firm Resolve','forgottenfragmenta.png','Forgotten Fragment of Resolve',8,'Bozjan Southern Front','CE: Trampled Under Hoof<br>CE: Where Strode the Behemoth<br>CE: Metal Fox Chaos'),
(14,'lostincense.png','Lost Incense','forgottenfragmenta.png','Forgotten Fragment of Caution',2,'Bozjan Southern Front','South Star Mobs'),
(15,'bannerofsolemnclarity.png','Banner of Solemn Clarity','forgottenfragmenta.png','Forgotten Fragment of Resolve',8,'Bozjan Southern Front','CE: Trampled Under Hoof<br>CE: Where Strode the Behemoth<br>CE: Metal Fox Chaos'),
(16,'lostcure.png','Lost Cure','forgottenfragmenta.png','Forgotten Fragment of Caution',2,'Bozjan Southern Front','South Star Mobs'),
(17,'lostcureii.png','Lost Cure II','forgottenfragmenta.png','Forgotten Fragment of Compassion',8,'Bozjan Southern Front','North Normal Mobs'),
(18,'lostcureiii.png','Lost Cure III','forgottenfragmenta.png','Forgotten Fragment of Caution',2,'Bozjan Southern Front','South Star Mobs'),
(19,'lostcureiv.png','Lost Cure IV','forgottenfragmenta.png','Forgotten Fragment of Compassion',8,'Bozjan Southern Front','North Normal Mobs'),
(20,'lostarise.png','Lost Arise','forgottenfragmenta.png','Forgotten Fragment of Compassion',8,'Bozjan Southern Front','North Normal Mobs'),
(21,'lostsacrifice.png','Lost Sacrifice','forgottenfragmentb.png','Forgotten Fragment of Loss',14,'Delubrum Reginae','Rare Drop from Loot Coffers'),
(22,'lostspellforge.png','Lost Spellforge','forgottenfragmenta.png','Forgotten Fragment of Ingenuity',5,'Bozjan Southern Front','Middle Star Mobs'),
(23,'loststeelsting.png','Lost Steelsting','forgottenfragmenta.png','Forgotten Fragment of Ingenuity',5,'Bozjan Southern Front','Middle Star Mobs'),
(24,'lostprotect.png','Lost Protect','forgottenfragmenta.png','Forgotten Fragment of Caution',2,'Bozjan Southern Front','South Star Mobs'),
(25,'lostshell.png','Lost Shell','forgottenfragmenta.png','Forgotten Fragment of Caution',2,'Bozjan Southern Front','South Star Mobs'),
(26,'lostreflect.png','Lost Reflect','forgottenfragmenta.png','Forgotten Fragment of Support',8,'Bozjan Southern Front','North Sprites'),
(27,'loststoneskin.png','Lost Stoneskin','forgottenfragmenta.png','Forgotten Fragment of Support',8,'Bozjan Southern Front','North Sprites'),
(28,'lostbravery.png','Lost Bravery','forgottenfragmenta.png','Forgotten Fragment of Support',8,'Bozjan Southern Front','North Sprites'),
(29,'lostaethershield.png','Lost Aethershield','forgottenfragmentb.png','Forgotten Fragment of Fortitude',15,'Bozjan Southern Front<br>Delubrum Reginae','Trade for 3 Bozjan Clusters<br>Rare Drop from Loot Coffers'),
(30,'lostdervish.png','Lost Dervish','forgottenfragmentb.png','Forgotten Fragment of Finesse',15,'Bozjan Southern Front<br>Delubrum Reginae','Trade for 3 Bozjan Clusters<br>Rare Drop from Loot Coffers'),
(31,'loststealth.png','Lost Stealth','forgottenfragmenta.png','Forgotten Fragment of Caution',2,'Bozjan Southern Front','South Star Mobs'),
(32,'lostswift.png','Lost Swift','forgottenfragmenta.png','Forgotten Fragment of Ingenuity',5,'Bozjan Southern Front','Middle Star Mobs'),
(33,'lostfontofskill.png','Lost Font of Skill','forgottenfragmenta.png','Forgotten Fragment of Sagacity',12,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(34,'mimic.png','Mimic','forgottenfragmenta.png','Forgotten Fragment of Caprice',15,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(35,'lostperception.png','Lost Perception','forgottenfragmentb.png','Forgotten Fragment of Observation',10,'Bozjan Southern Front','Trade for 1 Bozjan Cluster<br>Rare Drop from Loot Coffers'),
(36,'lostparalyzeiii.png','Lost Paralyze III','forgottenfragmenta.png','Forgotten Fragment of Ingenuity',5,'Bozjan Southern Front','Middle Star Mobs'),
(37,'lostbanishiii.png','Lost Banish III','forgottenfragmenta.png','Forgotten Fragment of Ingenuity',5,'Bozjan Southern Front','Middle Star Mobs'),
(38,'lostdispel.png','Lost Dispel','forgottenfragmenta.png','Forgotten Fragment of Ingenuity',5,'Bozjan Southern Front','Middle Star Mobs'),
(39,'lostrendarmor.png','Lost Rend Armor','forgottenfragmentb.png','Forgotten Fragment of Contention',15,'Bozjan Southern Front<br>Delubrum Reginae','Trade for 3 Bozjan Clusters<br>Rare Drop from Loot Coffers'),
(40,'lostseraphstrike.png','Lost Seraph Strike','forgottenfragmentb.png','Forgotten Fragment of Divinity',15,'Bozjan Southern Front<br>Delubrum Reginae','Trade for 3 Bozjan Clusters<br>Rare Drop from Loot Coffers'),
(41,'dynamisdice.png','Dynamis Dice','forgottenfragmenta.png','Forgotten Fragment of Caprice',15,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(42,'resistancephoenix.png','Resistance Phoenix','forgottenfragmenta.png','Forgotten Fragment of Preparation',2,'Bozjan Southern Front','South Ashkin, South Sprites'),
(43,'resistancereraiser.png','Resistance Reraiser','forgottenfragmenta.png','Forgotten Fragment of Care',5,'Bozjan Southern Front','Middle Ashkin, Middle Sprites'),
(44,'resistancepotionkit.png','Resistance Potion Kit','forgottenfragmenta.png','Forgotten Fragment of Care',5,'Bozjan Southern Front','Middle Ashkin, Middle Sprites'),
(45,'resistanceetherkit.png','Resistance Ether Kit','forgottenfragmenta.png','Forgotten Fragment of Care',5,'Bozjan Southern Front','Middle Ashkin, Middle Sprites'),
(46,'resistancemedkit.png','Resistance Medkit','forgottenfragmenta.png','Forgotten Fragment of Compassion',8,'Bozjan Southern Front','North Normal Mobs'),
(47,'resistancepotion.png','Resistance Potion','forgottenfragmenta.png','Forgotten Fragment of Preparation',2,'Bozjan Southern Front','South Ashkin, South Sprites'),
(48,'essenceoftheaetherweaver.png','Essence of the Aetherweaver','forgottenfragmenta.png','Forgotten Fragment of Skill',2,'Bozjan Southern Front','South Normal Mobs'),
(49,'essenceofthemartialist.png','Essence of the Martialist','forgottenfragmenta.png','Forgotten Fragment of Skill',2,'Bozjan Southern Front','South Normal Mobs'),
(50,'essenceofthesavior.png','Essence of the Savior','forgottenfragmenta.png','Forgotten Fragment of Skill',2,'Bozjan Southern Front','South Normal Mobs'),
(51,'essenceoftheveteran.png','Essence of the Veteran','forgottenfragmenta.png','Forgotten Fragment of Skill',2,'Bozjan Southern Front','South Normal Mobs'),
(52,'essenceoftheplatebearer.png','Essence of the Platebearer','forgottenfragmenta.png','Forgotten Fragment of Skill',2,'Bozjan Southern Front','South Normal Mobs'),
(53,'essenceoftheguardian.png','Essence of the Guardian','forgottenfragmenta.png','Forgotten Fragment of Awakening',5,'Bozjan Southern Front','Middle Normal Mobs'),
(54,'essenceoftheordained.png','Essence of the Ordained','forgottenfragmenta.png','Forgotten Fragment of Awakening',5,'Bozjan Southern Front','Middle Normal Mobs'),
(55,'essenceoftheskirmisher.png','Essence of the Skirmisher','forgottenfragmenta.png','Forgotten Fragment of Awakening',5,'Bozjan Southern Front','Middle Normal Mobs'),
(56,'essenceofthewatcher.png','Essence of the Watcher','forgottenfragmenta.png','Forgotten Fragment of Awakening',5,'Bozjan Southern Front','Middle Normal Mobs'),
(57,'essenceoftheprofane.png','Essence of the Profane','forgottenfragmenta.png','Forgotten Fragment of Awakening',5,'Bozjan Southern Front','Middle Normal Mobs'),
(58,'essenceoftheirregular.png','Essence of the Irregular','forgottenfragmenta.png','Forgotten Fragment of Awakening',5,'Bozjan Southern Front','Middle Normal Mobs'),
(59,'essenceofthebreathtaker.png','Essence of the Breathtaker','forgottenfragmenta.png','Forgotten Fragment of Awakening',5,'Bozjan Southern Front','Middle Normal Mobs'),
(60,'essenceofthebloodsucker.png','Essence of the Bloodsucker','forgottenfragmenta.png','Forgotten Fragment of Superstition',11,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(61,'essenceofthebeast.png','Essence of the Beast','forgottenfragmenta.png','Forgotten Fragment of Superstition',11,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(62,'essenceofthetemplar.png','Essence of the Templar','forgottenfragmenta.png','Forgotten Fragment of Superstition',11,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(63,'deepessenceoftheaetherweaver.png','Deep Essence of the Aetherweaver','forgottenfragmenta.png','Forgotten Fragment of Mastery',11,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(64,'deepessenceofthemartialist.png','Deep Essence of hte Martialist','forgottenfragmenta.png','Forgotten Fragment of Mastery',11,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(65,'deepessenceofthesavior.png','Deep Essence of the Savior','forgottenfragmenta.png','Forgotten Fragment of Mastery',11,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(66,'deepessenceoftheveteran.png','Deep Essence of the Veteran','forgottenfragmenta.png','Forgotten Fragment of Mastery',11,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(67,'deepessenceoftheplatebearer.png','Deep Essence of the Platebearer','forgottenfragmenta.png','Forgotten Fragment of Mastery',11,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(68,'deepessenceoftheguardian.png','Deep Essence of the Guardian','forgottenfragmenta.png','Forgotten Fragment of Becoming',13,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(69,'deepessenceoftheordained.png','Deep Essence of the Ordained','forgottenfragmenta.png','Forgotten Fragment of Becoming',13,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(70,'deepessenceoftheskirmisher.png','Deep Essence of the Skirmisher','forgottenfragmenta.png','Forgotten Fragment of Becoming',13,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(71,'deepessenceofthewatcher.png','Deep Essence of the Watcher','forgottenfragmenta.png','Forgotten Fragment of Becoming',13,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(72,'deepessenceoftheprofane.png','Deep Essence of the Profane','forgottenfragmenta.png','Forgotten Fragment of Becoming',13,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(73,'deepessenceoftheirregular.png','Deep Essence of the Irregular','forgottenfragmenta.png','Forgotten Fragment of Becoming',13,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(74,'deepessenceofthebreathtaker.png','Deep Essence of the Breathtaker','forgottenfragmenta.png','Forgotten Fragment of Becoming',13,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(75,'deepessenceofthebloodsucker.png','Deep Essence of the Bloodsucker','forgottenfragmenta.png','Forgotten Fragment of Transcendence',14,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(76,'deepessenceofthebeast.png','Deep Essence of the Beast','forgottenfragmenta.png','Forgotten Fragment of Transcendence',14,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(77,'deepessenceofthetemplar.png','Deep Essence of the Templar','forgottenfragmenta.png','Forgotten Fragment of Transcendence',14,'Bozjan Southern Front','CE: Battle for Castrum Lacus Litore'),
(78,'pureessenceofthegambler.png','Pure Essence of the Gambler','forgottenfragmentb.png','Forgotten Fragment of Deception',13,'Delubrum Reginae (Savage)',''),
(79,'pureessenceoftheelder.png','Pure Essence of the Elder','forgottenfragmentb.png','Forgotten Fragment of Clarity',15,'Bozjan Southern Front<br>Delubrum Reginae','Trade for 3 Bozjan Clusters<br>Rare Drop from Loot Coffers'),
(80,'pureessenceoftheduelist.png','Pure Essence of the Duelist','forgottenfragmentb.png','Forgotten Fragment of Contention',15,'Bozjan Southern Front<br>Delubrum Reginae','Trade for 3 Bozjan Clusters<br>Rare Drop from Loot Coffers'),
(81,'pureessenceofthefiendhunter.png','Pure Essence of the Fiendhunter','forgottenfragmentb.png','Forgotten Fragment of Finesse',15,'Bozjan Southern Front<br>Delubrum Reginae','Trade for 3 Bozjan Clusters<br>Rare Drop from Loot Coffers'),
(82,'pureessenceoftheindomitable.png','Pure Essence of the Indomitable','forgottenfragmentb.png','Forgotten Fragment of Fortitude',15,'Bozjan Southern Front<br>Delubrum Reginae','Trade for 3 Bozjan Clusters<br>Rare Drop from Loot Coffers'),
(83,'pureessenceofthedivine.png','Pure Essence of the Divine','forgottenfragmentb.png','Forgotten Fragment of Divinity',15,'Bozjan Southern Front<br>Delubrum Reginae','Trade for 3 Bozjan Clusters<br>Rare Drop from Loot Coffers')