function airships() {
    document.getElementById("airships").style.display = "block"
    document.getElementById("airbtn").style.borderColor = "#ccc"
    document.getElementById("submersibles").style.display = "none"
    document.getElementById("subbtn").style.borderColor = "#666"
}

function submersibles() {
    document.getElementById("submersibles").style.display = "block"
    document.getElementById("subbtn").style.borderColor = "#ccc"
    document.getElementById("airships").style.display = "none"
    document.getElementById("airbtn").style.borderColor = "#666"
}